#######################################################
# 
# GUI.py
# Python implementation of the Class GUI
# Generated by Enterprise Architect
# Created on:      20-1ÔÂ-2024 17:32:29
# Original author: N2308875D
# 
#######################################################


class GUI:
    """pyinstaller -F -w .\Python?-|?1?\exe?¨C????qt\main.py
    """
    def __init__(self):
        pass

    def DAG_Critical_Features_Set(self, temp_DAG_obj):
        pass

    def DAG_Data_Abstract(self):
        """(1) type 1
        """
        pass

    def DAG_Generator_Flow_Based(self):
        pass

    def DAG_Generator_Param_Based(self):
        pass

    def DAG_Param_Input(self):
        """(2) type 2
        """
        pass

    def Data_Critical_Features_Set(self, DAG_Feature):
        pass

    def Data_Trans_HTOS(self):
        pass

    def Flow_Data_InPut(self):
        """(3) type 3
        """
        pass

    def Input_Addr(self, path, Qedit):
        pass

    def Output_Data_SELF(self):
        pass